In [22]:
import os
import pandas as pd
from configs.config import cfg

eda_dir = cfg["eda_dir"]

In [23]:
df = pd.read_csv(cfg['data']['raw_root']+ "/Sampled_Sarcopenia_Data.csv")

df.head()

,MMSE,Age,Weight,Height,Waist,Hip,Smoking,Smoking (packet/year),Alcohol,DM,...,Working Status,Exercise,AT,CST,Gait Speed,Grip Strength,STAR,BMI,Sarcopenia,Gender
0,29.0,56.0,83.0,159.0,103.0,117.0,0.0,0.0,0,0.0,...,retired,0,41.2,9.10,1.0,34.0,1.26,32.80,0.0,F
1,29.0,52.0,75.0,162.0,94.0,107.0,0.0,0.0,0,1.0,...,working,0,46.7,9.30,1.1,28.0,1.63,28.58,0.0,F
2,NaN,67.0,79.0,150.0,NaN,NaN,0.0,0.0,0,1.0,...,emekli veya çalışmıyor,0,36.3,11.32,NaN,22.0,1.03,35.11,0.0,F
3,27.0,60.0,60.0,155.0,92.0,102.0,0.0,0.0,0,0.0,...,ÇALIŞIYOR,3-4/week,44.4,11.20,1.0,28.0,1.78,24.97,0.0,F
4,NaN,66.0,84.0,157.0,NaN,NaN,0.0,0.0,0,1.0,...,emekli veya çalışmıyor,0,25.1,13.40,NaN,16.0,0.74,34.00,1.0,F

In [24]:
# rename F -> Female and M -> Male

In [25]:
gender_counts = df["Gender"].value_counts()

def append_row_counts(output_data, row_counts):
    for row, count in row_counts.items():
        output_data.append([row, count])
    return output_data

output_data = [
    ["Sex", ""],
]

output_data = append_row_counts(output_data, gender_counts)
output_df = pd.DataFrame(output_data, columns=["Variable", "Count"])
output_df.to_excel(os.path.join(eda_dir,'Demographics.xlsx'), index=False)